info:
  id: ${spring.application.name}
logging:
  level:
    org.springframework.security: DEBUG
management.security.enabled: false
security:
  basic.enabled: false
  oauth2.resource.filter-order: 3

